server:
  port: 8080

spring:
  application:
    name: webflux-demo
  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux_demo
    username: root
    password: rlgus585
  sql:
    init:
      mode: always

jwt:
  secret: KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
  expiration-time: 86400000  # 24시간
